<?php
include_once("app/views/layouts/header-view.php");
include_once("app/views/layouts/slider-view.php");
include_once("app/views/layouts/cards-view.php");
include_once("app/views/layouts/offer-view.php");
include_once("app/views/layouts/courses-view.php");
include_once("app/views/layouts/certified-view.php");
include_once("app/views/layouts/quotes-view.php");
include_once("app/views/layouts/blogs-view.php");
include_once("app/views/layouts/footer-view.php");
?>